name:Docker image build using github actions

on:
  push:
    branch:
      -master
      -github-actions-test

jobs:
  docker-build:
    runs-on:ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-python-app .
